### ISSUE TITLE
Make sheet width and height configurable

### ISSUE THREAD

**Issue by ARolek** [go-spatial/maptoolkit#42]
Currently, the width and height of a sheet are hard coded. These should be configurable. The specific point in the code this needs to be addressed is: 

https://github.com/go-spatial/maptoolkit/blob/042b26e8b40508d69b6f28bd3412b28cad49f86d/atlante/atlante.go#L292

**Comment by roblabs** [comment]
For example, here are sample PDF size dimensions in `points` that could be used with Atlante

``` toml
[[sheets]]
  name = "grid50k"
  provider_grid = "PostgisDb"
  scale = 50000
  style = "file:///mnt/styles/bonn.json"
  template = "file:///mnt/templates/template_atlante.svg"
  size = [2028, 2607] # Hardcode value from atlante.go#L292
  # 2607, 2028        # Rotated 90° for `landscape`
  # 2337.12, 1765.44  # Other PDF size, 32.46 × 24.52
  # 3412, 4350        # USGS US Topo `gdalinfo file.pdf | grep Size`
  # 3262, 4050        # USFS FSTopo, https://roblabs.com/gdal-geopdf
  # 1584.8, 2449.4    # https://papersizes.io/us/ansi-d, 22 × 34 inches
  # 1729.3, 2591.2    # https://papersizes.io/us/arch-d, 24 × 36 inches
```

### Implementation research 

* Option 1 — implement in `toml` as two variables, or as an array 
* Option 2 — Pass in the Size at the command line to `atlante`, e.g., `--width 3262 --height 4050`

**Comment by gdey** [comment]
I'm thinking of width and  height be presented in mm. So the config would look like:
```toml

[[sheets]]
   name = "grid50k"
  provider_grid = "PostgisDb50k"
  style = "file://mnt/styles/bonn.json"
  template = "file:///mnt/templates/template_atlante.svg"
 # A0 in protrait mode
  width = 841 # in mm
  height = 1189 # in mm

```
The system will convert the mm into points. (I think we should handle, because if we change the render then these sizes would not have to change. Right now we are doing 72 dots per inch, but this could change later.)

**Comment by roblabs** [comment]
There is an error in the scalar conversion from the `config.toml` units to inches.  

See, 
* https://github.com/go-spatial/maptoolkit/blob/width_height_edit_date/atlante/sheet.go#L107
* https://github.com/go-spatial/maptoolkit/blob/width_height_edit_date/atlante/sheet.go#L118

Example, 

The `DefaultHeightMM = 28.16667` is scaled by 

``` go 
 # dividing by mm2inch results in scaling by 25.4^2
return mm * float64(dpi) / mm2inch  
 # Should be '*' by mm2inch
```

when it should be scaled by 

``` go 
return mm * float64(dpi) * mm2inch
```
Where `mm2inch = 1 / 25.4`


### Empirical Testing Results

All these PDF inch sizes are off by a factor of 25.4^2 = 645.16
---

| `config.toml` values (source says MM) | Resulting PDF (inches)  |
| :------------- | :------------- |
 *A0, per comments*
 | `width = 841.0`    |  21361.4 inches
  `height = 1189.0`    | 30200.61 inches
*Default with no width height passed in.  Source says 36.20833 x 28.16667 mm*
| `# width = 841.0`    |  715.44
 `# height = 1189.0`    | 919.7
*Expect 10"x10" PDF*
 | `width = 254.0`    | 6451.6
  `height = 254.0`    | 6451.6
*Dummy test value to see what went wrong*
  | `width = 100.0`    |  254 
   `height = 100.0`    | 254  
From the source


---

| `config.toml` values (source says MM) | Resulting PDF (inches)  |
| :------------- | :------------- |
 *A0, per comments*
 | `width = 841.0`    |  21361.4 inches
  `height = 1189.0`    | 30200.61 inches
*Default with no width height passed in.  Source says 36.20833 x 28.16667 mm*
| `# width = 841.0`    |  715.44
 `# height = 1189.0`    | 919.7
*Expect 10"x10" PDF*
 | `width = 254.0`    | 6451.6
  `height = 254.0`    | 6451.6
*Dummy test value to see what went wrong*
  | `width = 100.0`    |  254 
   `height = 100.0`    | 254

**Comment by gdey** [comment]
Good catch. I got the math confused when transcribing from my note pad to code.

**Comment by roblabs** [comment]
### Test Results 

Using atlante image built on Jun 19 —

``` console
# docker images | grep atlante
gospatial/atlante       latest                     99418b854edd        4 hours ago         663MB
```

| `config.toml` values (source says MM) | Resulting PDF (inches)  |
| :------------- | :------------- |
 *A0, per comments*
 | `width = 841.0`    |  21361.4 inches
  `height = 1189.0`    | 30200.61 inches
*Default with no width height passed in.  Source says 36.20833 x 28.16667 mm*
| `# width = 841.0`    |  46.82 × 33.12 inches
 `# height = 1189.0`    | 
*Expect 10"x10" PDF*
 | `width = 254.0`    | 10 × 10 inches
  `height = 254.0`    | 
*Dummy test values*
  | `width = 100.0`    |  3.94 × 3.94 inches 
   `height = 100.0`    |

**Comment by gdey** [comment]
Add fix and test cases for this: #51

**Comment by roblabs** [comment]
New issue related to `config.toml`

* **The height and width parameters are flipped in the PDF generation**
* For example, this `toml` gives a PDF that is the wrong size
 * height = 824.48   # Expect 32.46 high × 24.52 wide inches
 * width = 622.81    # 2337.11 × 1765.45 points

_workaround, for now, is to swap values until this is fixed_

``` toml
[[sheets]]
  name          = "new_grid_size"
  provider_grid = "PostgisDb50K"
  style         = "file:///mnt/styles/bonn.json"
  template      = "file:///mnt/templates/arbitrary_template_atlante.svg"
  height = 824.48   # 32.46 × 24.52 inches, for 250k Landscape sheet
  width = 622.81    # 2337.11 × 1765.45 points
```

![width-height-flipped](https://user-images.githubusercontent.com/118112/60134836-43fa4400-9755-11e9-9dff-c47d4f2e00e5.png)
