### ISSUE TITLE
Proxy URL for server

### ISSUE THREAD

**Issue by gdey** [go-spatial/maptoolkit#47]
#17 
One of the urls listed in #17 is the proxy. We are pulling that out of #17 into this issue.

Changes to the config:
Webserver section should now have an additional config called `proxy_path` which is a string.

```toml
[webserver]
   proxy_path='http://localhost:9090/sheets/{{.SheetName}}/files/mgdid/${{.MGDID}}.pdf'
```

This is what will be filled into the `pdf_url` field for info. 
It will disable the querying the filestores for urls.
This will enable the `/sheet/${sheetname}/files/mgdid/${mdgid}.pdf` end point on the server.
This end point will query the filestores for an io.Reader used to proxy the file.
