### ISSUE TITLE
[config] sheet width and height are inverse 

### ISSUE THREAD

**Issue by ARolek** [go-spatial/maptoolkit#66]
The config mapping to width and height are inversed when the sheet is generated.

**Comment by gdey** [comment]
New issue related to `config.toml`

* **The height and width parameters are flipped in the PDF generation**
* For example, this `toml` gives a PDF that is the wrong size
 * height = 824.48   # Expect 32.46 high × 24.52 wide inches
 * width = 622.81    # 2337.11 × 1765.45 points

_workaround, for now, is to swap values until this is fixed_

``` toml
[[sheets]]
  name          = "new_grid_size"
  provider_grid = "PostgisDb50K"
  style         = "file:///mnt/styles/bonn.json"
  template      = "file:///mnt/templates/arbitrary_template_atlante.svg"
  height = 824.48   # 32.46 × 24.52 inches, for 250k Landscape sheet
  width = 622.81    # 2337.11 × 1765.45 points
```

![width-height-flipped](https://user-images.githubusercontent.com/118112/60134836-43fa4400-9755-11e9-9dff-c47d4f2e00e5.png)

_Originally posted by @roblabs in https://github.com/go-spatial/maptoolkit/issues/42#issuecomment-505630338_
